name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Built-in GitHub token
        with:
          args: detect --verbose

      # --- 1. SAST: Scanning your custom code logic ---
      - name: Run Snyk to check for code vulnerabilities
        uses: snyk/actions/node@master # Use 'python' or 'golang' depending on your app
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      # --- 2. SCA: Scanning your libraries/dependencies ---
      - name: Run Trivy FS scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

      # --- 3. BUILD: If code and libraries are safe, build the image ---
      - name: Build image locally
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true 
          tags: chandru0509/my-app:v1

      # --- 4. IMAGE SCAN: Scan the final container OS ---
      - name: Run Trivy image scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'chandru0509/my-app:v1'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
     
      - name: Push Docker Image
        run: docker push chandru0509/my-app:v1